import { Suspense } from 'react';
import { NavigationEvents } from '@/component/NavigationEvents';
import { Poppins } from 'next/font/google';
import { ThemeProvider } from '@/component/Theme'
import './globals.css'

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--poppins-font',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <ThemeProvider>
          {children}
          <Suspense fallback={null}>
            <NavigationEvents />
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  )
}